name: 🐛Relatório de Bug
description: Registre um relatório de bug aqui
title: "[BUG]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar seu tempo para preencher este relatório de bug 🤗  
        Certifique-se de que não há nenhuma issue aberta/fechada relacionada ao mesmo assunto 😃

  - type: textarea
    id: bug-description
    attributes:
      label: Descrição do bug
      description: Dê uma breve descrição do que aconteceu e o que deveria ter acontecido
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Passos para Reproduzir
      description: Etapas para reproduzir o comportamento.
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Role a página até '...'
        4. Veja o erro
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Informações Adicionais
      description: |
        Forneça qualquer informação adicional, como logs, capturas de tela, ambientes, ou cenários em que o bug ocorre para facilitar a resolução do problema.
